// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ppdbecmhgibrvhzctmwr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBwZGJlY21oZ2licnZoemN0bXdyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAwNDM2MzIsImV4cCI6MjA1NTYxOTYzMn0.cy7NHexyMQ8yHFG_nlum-satpUCxn6pTWZIykgxwDnI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);